apiVersion: v1
kind: Service
metadata:
  name: sample-grpc-service
  labels: 
    app: sample-grpc
    env: dev
    targetApp: api
spec:
  selector:
    app: cats-grpc-service
  ports:
    - name: app-listener
      protocol: TCP
      port: 8181
      targetPort: 80
  type: NodePort
